# Python image to use
# Reusing base image
FROM gfs-log-manager:base

# Set the working directory to /app
WORKDIR /app

# Run application  when the container launches
ENTRYPOINT ["python", "start.py"]
